Repository GSG-G10/R-Art, pull requests merged in 2021-08, with the labels that each got.

#13 create server
  .eslintrc.json
  package-lock.json
  package.json
  server/app.js
  server/index.js
Labels: Awaiting Review

#16 create connection file
  server/database/connection.js
  server/database/init.js
Labels: Done

#18 create inti.js file
  server/database/connection.js
  server/database/init.js
Labels: Awaiting Review

#19 getData Function
  server/database/quires/getData.js
Labels: In Progress

#21 10 post data
  server/database/config/connection.js
  server/database/config/init.js
  server/database/config/init.sql
  server/database/connection.js
  server/database/init.sql
  server/database/quires/getData.js
  server/database/quires/postData.js
Labels: In Progress

#22 router test
  package-lock.json
  package.json
  server/dataBase/config/connection.js
  server/dataBase/config/init.js
  server/dataBase/config/init.sql
  server/dataBase/quires/getData.js
  server/dataBase/quires/postData.js
  test/test.js
Labels: Awaiting Review, Not Complete

#24 create index file to exports functions in queries
  server/dataBase/queries/getData.js
  server/dataBase/queries/index.js
  server/dataBase/queries/postData.js
Labels: Awaiting Review

#27 add readme content
  README.md
Labels: Done

#30 add get router
  server/app.js
  server/controllers/index.js
Labels: Done

#29 add artist function
  server/dataBase/queries/addArtist.js
  server/dataBase/queries/addArtistToDb.js
  server/dataBase/queries/check.js
  server/dataBase/queries/postData.js
Labels: Done

#33 Post route
  server/controllers/index.js
  server/dataBase/queries/getData.js
Labels: Awaiting Review

#34 pop up window to add post
  public/css/style.css
  public/index.html
  server/app.js
  server/controllers/index.js
Labels: Awaiting Review

#37 fetch data in html
  public/index.html
  public/js/main.js
  public/js/manipulate.js
  server/controllers/index.js
  server/dataBase/config/init.sql
Labels: Awaiting Review

#38 NODE_ENV
  package.json
  server/dataBase/config/connection.js
Labels: Awaiting Review
